---
- name: Setup GPG key from docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Setup docker apt repository for ubuntu
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker packages
  become: yes
  apt:
    name: "{{ docker_packages }}"
    state: present
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
